# Generated by Django 4.1.3 on 2022-12-11 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='art',
            name='type',
            field=models.CharField(choices=[('painting', 'painting'), ('sculpture', 'sculpture'), ('graffiti', 'graffiti')], default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='art',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
